(deftheme blacks
  "Created 2017-10-09.")

(custom-theme-set-variables
 'blacks
 '(ansi-color-names-vector ["#000000" "#fb0120" "#a1c659" "#fda331" "#6fb3d2" "#d381c3" "#6fb3d2" "#e0e0e0"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'blacks
 '(bold ((t (:bold t))))
 '(bold-italic ((t (:bold t :slant italic))))
 '(underline ((nil (:underline nil))))
 '(italic ((t (nil))))
 '(font-lock-builtin-face ((t (:foreground "#fff"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#666"))))
 '(font-lock-comment-face ((t (:foreground "#666"))))
 '(font-lock-constant-face ((t (:foreground "#bf5c00"))))
 '(font-lock-doc-face ((t (:foreground "green"))))
 '(font-lock-function-name-face ((t (:foreground "#ddd"))))
 '(font-lock-keyword-face ((t (:foreground "#d283d1"))))
 '(font-lock-negation-char-face ((((type graphic)) (:foreground "#a1c659")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(font-lock-preprocessor-face ((t (:foreground "#ddd"))))
 '(font-lock-regexp-grouping-backslash ((((type graphic)) (:foreground "#fda331")) (((min-colors 256)) (:foreground "yellow")) (t (:foreground "yellow"))))
 '(font-lock-regexp-grouping-construct ((((type graphic)) (:foreground "#d381c3")) (((min-colors 256)) (:foreground "magenta")) (t (:foreground "magenta"))))
 '(font-lock-string-face ((((type graphic)) (:foreground "#a1c659")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(font-lock-type-face ((t (:foreground "#ddd"))))
 '(font-lock-variable-name-face ((t (:foreground "#ddd"))))
 '(font-lock-warning-face ((((type graphic)) (:foreground "#fb0120")) (((min-colors 256)) (:foreground "red")) (t (:foreground "red"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(success ((((type graphic)) (:foreground "#a1c659" :weight bold)) (((min-colors 256)) (:foreground "green" :weight bold)) (t (:foreground "green" :weight bold))))
 '(error ((((type graphic)) (:foreground "#fb0120" :weight bold)) (((min-colors 256)) (:foreground "red" :weight bold)) (t (:foreground "red" :weight bold))))
 '(warning ((((type graphic)) (:foreground "#fc6d24" :weight bold)) (((min-colors 256)) (:foreground "brightred" :weight bold)) (t (:foreground "brightred" :weight bold))))
 '(tooltip ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#000000" :inverse-video t))))
 '(window-divider ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(window-divider-first-pixel ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(window-divider-last-pixel ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(flycheck-error ((((type graphic)) (:underline (:style wave :color "#fb0120"))) (((min-colors 256)) (:underline (:style wave :color "red"))) (t (:underline (:style wave :color "red")))))
 '(flycheck-info ((((type graphic)) (:underline (:style wave :color "#a1c659"))) (((min-colors 256)) (:underline (:style wave :color "green"))) (t (:underline (:style wave :color "green")))))
 '(flycheck-warning ((((type graphic)) (:underline (:style wave :color "#fc6d24"))) (((min-colors 256)) (:underline (:style wave :color "brightred"))) (t (:underline (:style wave :color "brightred")))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(flyspell-incorrect ((((type graphic)) (:underline (:style wave :color "#fb0120"))) (((min-colors 256)) (:underline (:style wave :color "red"))) (t (:underline (:style wave :color "red")))))
 '(match ((t (:background "#505050" :foreground "white"))))
 '(isearch ((((type graphic)) (:foreground "#fda331" :background "#303030" :inverse-video t)) (((min-colors 256)) (:foreground "yellow" :background "brightgreen" :inverse-video t)) (t (:foreground "yellow" :background "brightgreen" :inverse-video t))))
 '(lazy-highlight ((((type graphic)) (:foreground "#76c7b7" :background "#303030" :inverse-video t)) (((min-colors 256)) (:foreground "cyan" :background "brightgreen" :inverse-video t)) (t (:foreground "cyan" :background "brightgreen" :inverse-video t))))
 '(isearch-fail ((((type graphic)) (:background "#303030" :inverse-video t :inherit font-lock-warning-face)) (((min-colors 256)) (:background "brightgreen" :inverse-video t :inherit font-lock-warning-face)) (t (:background "brightgreen" :inverse-video t :inherit font-lock-warning-face))))
 '(cursor ((t (:background "#d0d0d0"))))
 '(fringe ((((type graphic)) (:background "#505050")) (((min-colors 256)) (:background "brightyellow")) (t (:background "brightyellow"))))
 '(linum ((t (:background "black" :foreground "#2d2d2d"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#424242"))))
 '(border ((t (:background "#505050"))))
 '(highlight ((t (:background "#3a3a3a"))))
 '(mode-line ((t (:background "#505050" :foreground "#d0d0d0" :box nil))))
 '(mode-line-buffer-id ((((type graphic)) (:foreground "#a1c659" :background nil)) (((min-colors 256)) (:foreground "green" :background nil)) (t (:foreground "green" :background nil))))
 '(mode-line-inactive ((((type graphic)) (:foreground "#b0b0b0" :background "#303030" :box nil)) (((min-colors 256)) (:foreground "brightblack" :background "brightgreen" :box nil)) (t (:foreground "brightblack" :background "brightgreen" :box nil))))
 '(mode-line-emphasis ((((type graphic)) (:foreground "#f5f5f5" :slant italic)) (((min-colors 256)) (:foreground "brightmagenta" :slant italic)) (t (:foreground "brightmagenta" :slant italic))))
 '(mode-line-highlight ((((type graphic)) (:foreground "#d381c3" :box nil :weight bold)) (((min-colors 256)) (:foreground "magenta" :box nil :weight bold)) (t (:foreground "magenta" :box nil :weight bold))))
 '(minibuffer-prompt ((((type graphic)) (:foreground "#6fb3d2")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(region ((t (:background "#3a3a3a"))))
 '(secondary-selection ((t (:background "#505050"))))
 '(header-line ((((type graphic)) (:foreground "#d381c3" :background nil :inherit mode-line)) (((min-colors 256)) (:foreground "magenta" :background nil :inherit mode-line)) (t (:foreground "magenta" :background nil :inherit mode-line))))
 '(trailing-whitespace ((((type graphic)) (:foreground "#fda331" :background "#76c7b7")) (((min-colors 256)) (:foreground "yellow" :background "cyan")) (t (:foreground "yellow" :background "cyan"))))
 '(show-paren-match ((t (:background "#505050" :foreground "white"))))
 '(show-paren-mismatch ((((type graphic)) (:foreground "#303030" :background "#fc6d24")) (((min-colors 256)) (:foreground "brightgreen" :background "brightred")) (t (:foreground "brightgreen" :background "brightred"))))
 '(eldoc-highlight-function-argument ((((type graphic)) (:foreground "#a1c659" :weight bold)) (((min-colors 256)) (:foreground "green" :weight bold)) (t (:foreground "green" :weight bold))))
 '(undo-tree-visualizer-default-face ((((type graphic)) (:foreground "#f5f5f5")) (((min-colors 256)) (:foreground "brightmagenta")) (t (:foreground "brightmagenta"))))
 '(undo-tree-visualizer-current-face ((((type graphic)) (:foreground "#a1c659" :weight bold)) (((min-colors 256)) (:foreground "green" :weight bold)) (t (:foreground "green" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((type graphic)) (:foreground "#fb0120")) (((min-colors 256)) (:foreground "red")) (t (:foreground "red"))))
 '(undo-tree-visualizer-register-face ((((type graphic)) (:foreground "#fda331")) (((min-colors 256)) (:foreground "yellow")) (t (:foreground "yellow"))))
 '(link ((((type graphic)) (:foreground "#6fb3d2" :underline t)) (((min-colors 256)) (:foreground "blue" :underline t)) (t (:foreground "blue" :underline t))))
 '(widget-button ((((type graphic)) (:underline t)) (((min-colors 256)) (:underline t)) (t (:underline t))))
 '(widget-field ((((type graphic)) (:box (:line-width 1 :color "#f5f5f5") :background "#505050")) (((min-colors 256)) (:box (:line-width 1 :color "brightmagenta") :background "brightblack")) (t (:box (:line-width 1 :color "brightmagenta") :background "brightblack"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:inherit warning))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(helm-ff-dotted-symlink-directory ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(helm-match ((((class color) (min-colors 89)) (:inherit match))))
 '(helm-selection ((((class color) (min-colors 89)) (:inherit highlight))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:weight bold :foreground "#e78c45" :height 1.44))))
 '(Info-quoted ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(info-index-match ((((class color) (min-colors 89)) (:inherit isearch))))
 '(info-menu-header ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold :height 1.4))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold :slant italic))))
 '(info-title-1 ((((class color) (min-colors 89)) (:weight bold :height 1.6))))
 '(info-title-2 ((((class color) (min-colors 89)) (:weight bold :height 1.4))))
 '(info-title-3 ((((class color) (min-colors 89)) (:weight bold :height 1.2))))
 '(info-title-4 ((((class color) (min-colors 89)) (:weight bold))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:foreground "#969896" :underline t))))
 '(custom-variable-tag ((((type graphic)) (:foreground "#6fb3d2")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(custom-group-tag ((((type graphic)) (:foreground "#6fb3d2")) (((min-colors 256)) (:foreground "blue")) (t (:foreground "blue"))))
 '(custom-state ((((type graphic)) (:foreground "#a1c659")) (((min-colors 256)) (:foreground "green")) (t (:foreground "green"))))
 '(link-visited ((((type graphic)) (:foreground "#d381c3" :underline t)) (((min-colors 256)) (:foreground "magenta" :underline t)) (t (:foreground "magenta" :underline t))))
 '(clojure-keyword-face ((t (:foreground "#ddd"))))
 '(flyspell-duplicate ((((type graphic)) (:underline (:style wave :color "#fc6d24"))) (((min-colors 256)) (:underline (:style wave :color "brightred"))) (t (:underline (:style wave :color "brightred")))))
 '(default ((t (:background "black" :foreground "white")))))

(provide-theme 'blacks)
